
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poktroll.fullname" . }}
  labels:
    app: {{ include "poktroll.fullname" . }}
spec:
  selector:
    app: {{ include "poktroll.fullname" . }}
  ports:
    - protocol: TCP
      name: rpc
      port: 36657
      targetPort: 36657
    - protocol: TCP
      name: grpc
      port: 36658
      targetPort: 36658
    - port: 1317
      targetPort: api
      protocol: TCP
      name: api
