apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "path.fullname" . }}
  labels:
    {{- include "path.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ toYaml .Values.config | nindent 4 }}