apiVersion: v1
kind: Service
metadata:
  name: {{ include "path.fullname" . }}
  labels:
    {{- include "path.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "path.selectorLabels" . | nindent 4 }}
