replicaCount: 1 # This should never be more than 1 until Rollkit supports decentralized sequencers

configsConfigMapName: poktrolld-configs # TODO(@okdas): provision in the chart
keysConfigMapName: poktrolld-keys # TODO(@okdas): provision in the chart

image:
  repository: ghcr.io/pokt-network/poktrolld
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  rpcPort: 36657
pvc:
  accessModes: 
    - ReadWriteOnce
  requests:
    storage: 1Gi
dataAvailability:
  provider: celestia
  authToken:
    secretName: celestia-secret
    secretKey: auth_token
  celestia:
    hostname: celestia-rollkit
podSecurityContext: {}
  # allowPrivilegeEscalation: true
  # capabilities:
  #   add: ["SYS_PTRACE"]