apiVersion: v1
kind: Service
metadata:
  name: {{ include "relayminer.fullname" . }}
  labels:
    {{- include "relayminer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    - port: {{ .Values.ping.port }}
      targetPort: {{ .Values.ping.port }}
      protocol: TCP
      name: status
  selector:
    {{- include "relayminer.selectorLabels" . | nindent 4 }}
