
{{ if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "relayminer.fullname" . }}
  labels:
    {{- include "relayminer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "relayminer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
{{ end }}