{{ if .Values.relayer.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poktroll.fullname" . }}
  labels:
    {{- include "poktroll.labels" . | nindent 4 }}
    pokt.network/purpose: relayer
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "poktroll.selectorLabels" . | nindent 6 }}
      pokt.network/purpose: relayer
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "poktroll.labels" . | nindent 8 }}
        pokt.network/purpose: relayer
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "poktroll.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/bin/sh"]
          args: ["/scripts/pocket.sh"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8545
            - containerPort: 8546
            # TODO(@okdas): parametrize
            - containerPort: 40005
          livenessProbe:
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
            - name: keys-volume
              mountPath: /root/.pocket/keyring-test/
            - name: configs-volume
              mountPath: /root/.pocket/config-src/
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: keys-volume
          configMap:
            name: {{ .Values.keysConfigMapName }}
        - name: configs-volume
          configMap:
            name: {{ .Values.configsConfigMapName }}
        - name: scripts-volume
          configMap:
            name: {{ include "poktroll.fullname" . }}-scripts
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}