apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appgate-server.fullname" . }}
  labels:
    {{- include "appgate-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ toYaml .Values.config | nindent 4 }}