apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poktroll.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "poktroll.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "poktroll.fullname" . }}
        pokt.network/purpose: sequencer
    spec:
      containers:
        - name: poktrolld-sequencer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
{{ toYaml .Values.podSecurityContext | indent 12 }}
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dataAvailability.authToken.secretName }}
                  key: {{ .Values.dataAvailability.authToken.secretKey }}
            - name: CELESTIA_HOSTNAME
              value: {{ .Values.dataAvailability.celestia.hostname }}
          ports:
            - containerPort: {{ .Values.service.rpcPort }}
              name: rpc
            - containerPort: 40004 # TODO(@okdas): remove this - currently only needed for LocalNet dlv
              name: debug
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.rpcPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.rpcPort }}
          command: ["/bin/sh"]
{{ if .Values.prod.enabled }}
          args: ["/scripts/prod.sh"]
{{ else }}
          args: ["/scripts/dev.sh"]
{{ end }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
            - name: keys-volume
              mountPath: /root/.pocket/keyring-test/
            - name: configs-volume
              mountPath: /root/.pocket/config-src/
            - name: data-volume
              mountPath: /root/.pocket/data/
      volumes:
        - name: scripts-volume
          configMap:
            name: {{ include "poktroll.fullname" . }}-scripts
        - name: keys-volume
          configMap:
            name: {{ .Values.keysConfigMapName }}
        - name: configs-volume
          configMap:
            name: {{ .Values.configsConfigMapName }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "poktroll.fullname" . }}-data
