apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poktroll.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
