apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poktroll.fullname" . }}-scripts
data:
  pocket.sh: |-
    #!/bin/sh

    # reset any existing genesis/chain data
    rm -rf /root/.pocket/data/*
    echo '{"height":"0","round":0,"step":0}' > /root/.pocket/data/priv_validator_state.json

    # create a random Namespace ID for your rollup to post blocks to
    openssl rand -hex 8 > /root/.pocket/data/namespace-id
    NAMESPACE=$(cat /root/.pocket/data/namespace-id)

    # query the DA Layer start height, in this case we are querying
    # our local devnet at port 26657, the RPC. The RPC endpoint is
    # to allow users to interact with Celestia's nodes by querying
    # the node's state and broadcasting transactions on the Celestia
    # network. The default port is 26657.
    curl http://{{ .Values.dataAvailability.celestia.hostname }}:26657/block | jq -r '.result.block.header.height' > /root/.pocket/data/da-block-height
    DA_BLOCK_HEIGHT=$(cat /root/.pocket/data/da-block-height)

    echo "AUTH_TOKEN is: $AUTH_TOKEN"
    echo -e "Your NAMESPACE is $NAMESPACE \n\n Your DA_BLOCK_HEIGHT is $DA_BLOCK_HEIGHT"

    # ls -la /root/.pocket/config-src/
    mkdir -p /root/.pocket/config/
    cp -r -L /root/.pocket/config-src/* /root/.pocket/config/
    ls -la /root/.pocket/config/
    echo "\n/root/.pocket/config/priv_validator_key.json:"
    cat /root/.pocket/config/priv_validator_key.json
    echo "\n/root/.pocket/config/node_key.json:"
    cat /root/.pocket/config/node_key.json
    echo "\n/root/.pocket/config/genesis.json | jq '.validators':"
    cat /root/.pocket/config/genesis.json | jq '.validators'

    # sleep 9999

    # start the node
    # You can attach to this process with delve (dlv) for debugging purpose with `dlv attach $(pgrep poktrolld) --listen :40004 --headless --api-version=2 --accept-multiclient` - run inside the container!
    poktrolld start --home=/root/.pocket/ --rollkit.aggregator=true --rollkit.da_layer=celestia --rollkit.da_config='{"base_url":"http://{{ .Values.dataAvailability.celestia.hostname }}:26658","timeout":60000000000,"fee":600000,"gas_limit":6000000,"auth_token":"'$AUTH_TOKEN'"}' --rollkit.namespace_id=$NAMESPACE --rollkit.da_start_height=$DA_BLOCK_HEIGHT --rpc.laddr=tcp://0.0.0.0:36657 --p2p.laddr="0.0.0.0:36656"

    # OR debug the node (uncomment this line but comment previous line)
    # dlv exec /usr/local/bin/poktrolld --listen :40004 --headless --api-version=2 --accept-multiclient -- start --home=/root/.pocket/ --rollkit.aggregator=true --rollkit.da_layer=celestia --rollkit.da_config='{"base_url":"http://{{ .Values.dataAvailability.celestia.hostname }}:26658","timeout":60000000000,"fee":600000,"gas_limit":6000000,"auth_token":"'$AUTH_TOKEN'"}' --rollkit.namespace_id=$NAMESPACE --rollkit.da_start_height=$DA_BLOCK_HEIGHT --rpc.laddr=tcp://0.0.0.0:36657 --p2p.laddr="0.0.0.0:36656"

